program = jive

subdirs = ../src/utils  ../src/materials ../src/models ../src/modules  

include $(JIVEDIR)/makefiles/prog.mk
include $(JIVEDIR)/makefiles/packages/*.mk

MY_LIBS += boost_filesystem boost_system
MY_INCDIRS = ../src 
MY_CXX_FLAGS += -O2
